cmd/root.go
kai.yaml
kai/lib.go

Fixes #14 
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

Remove some code duplication around listing namespaces

---

.github/workflows/release.yaml

Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

Use implicit github token for releases

---

internal/config/config.go
internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
kai.yaml
kai/lib.go

Add the ability to exclude namespaces based on a list of direct strings to match or a list of regex patterns.

Add the ability to exclude namespaces

---

README.md

Signed-off-by: James Petersen <jpetersenames@gmail.com>

Add the readme updates for all new configurations

---

README.md
internal/config/config.go
internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
kai.yaml
kai/lib.go

Signed-off-by: James Petersen <jpetersenames@gmail.com>

Add backwards compatibility for kai configuration

---

.goreleaser.yaml
Dockerfile
Makefile

Signed-off-by: Weston Steimel <weston.steimel@anchore.com>

support building aarch64 binaries for linux and mac

---

install.sh

Signed-off-by: Weston Steimel <weston.steimel@anchore.com>

support arm64 in install.sh

---

.github/workflows/static-unit-integration.yaml
kai/inventory/reportitem_test.go

test: new test case for no repo info in imageid

---

.golangci.yaml
Makefile
internal/config/config.go
internal/version/update_test.go
kai/inventory/reportitem_test.go
kai/mode/mode.go
kai/presenter/json/presenter_test.go
kai/presenter/table/presenter_test.go
kai/reporter/reporter.go
kai/reporter/reporter_test.go
main.go
test/integration/get_images_test.go

Match config of golangci-lint to match other anchore repos (syft)

chore: update golangci-lint to latest version and update config

---

Makefile
install.sh

build: set GOARCH to arm64 on linux/mac arm builds

---

.github/workflows/acceptance-test.yaml
.github/workflows/release.yaml
.github/workflows/static-unit-integration.yaml
go.mod
internal/logger/logrus.go

feat: update to golang 1.19

---

.github/workflows/acceptance-test.yaml

ci: update the gpg key used for signing in acceptance-tests

---

.github/workflows/acceptance-test.yaml

- ci: update the gpg key used for signing in acceptance-tests
- ci: update ghaction-import-gpg version

ci: backport acceptance test ci fixes

---

.github/workflows/release.yaml

ci: fix release workflow test names

---

.github/workflows/release.yaml

ci: update gpg key used for release

---

.github/workflows/release.yaml

feat: update release gpg key

---

kai/lib.go
kai/reporter/reporter.go

chore: remove unused config arg in reporter Post

---

.goreleaser.yaml

chore: mark pre-release builds as pre-release

---

.goreleaser.yaml

Should have been removed when gpg signed-artifacts was.

chore: remove signing of artifacts

---

pkg/inventory/containers.go
pkg/inventory/containers_test.go

fix: ensure can get image tag from container status is spec is missing

---

pkg/inventory/containers.go
pkg/inventory/containers_test.go
pkg/lib.go

fix: ensure ignoreNotRunning config option is respected getting pods

---

pkg/inventory/containers.go
pkg/inventory/containers_test.go
pkg/lib.go

- fix: ensure ignoreNotRunning config option is respected getting pods
- fix: ensure missingTagPolicy is applied to all containers

fix: ensure missingTagPolicy is applied to all containers

---

README.md
internal/config/config.go
internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
pkg/inventory/namespace.go
pkg/inventory/namespace_test.go
pkg/inventory/pods.go
pkg/inventory/pods_test.go
pkg/lib.go

This will be reaccessed in a future release. All posts to Anchore
Enterprise from k8s-inventory will include all available metadata.

feat: remove metadata config option

---

.golangci.yaml
.goreleaser.yaml

chore: update goreleaser config for generating changelog

---

README.md

docs: fix broken link to docker image

---

.goreleaser.yaml

fix: ensure fips binary static linking is working correctly

---

go.mod
go.sum
pkg/reporter/reporter.go
pkg/reporter/reporter_test.go

https://anchore.atlassian.net/browse/ENTERPRISE-2926

fix: address the v2 api endpoint

---

pkg/reporter/reporter.go

fix: log formatting of retry message

---

pkg/reporter/reporter.go

chore: only nosec G402 on the specfic lines rather than the function

---

.github/dependabot.yml

chrore: add dependabot config

---

.github/workflows/codeql-analysis.yml

ci: update codeql action

---

.github/workflows/codeql-analysis.yml
.github/workflows/release.yaml
.github/workflows/static-unit-integration.yaml

- ci: pin setup-go to hash
- ci: pin checkout action to commit hash
- ci: pin action-wait-for-check github action to commit hash
- ci: pin cache action to commit hash
- ci: pin upload-artifact action to commit hash
- ci: pin kind-action github action to commit hash

ci: ensure github action are pinned to commit hash

---

.github/workflows/release.yaml
.github/workflows/static-unit-integration.yaml
go.mod
scripts/install-go.sh

feat: bump go version to 1.22

---

anchore-k8s-inventory.yaml
cmd/root.go
internal/config/config.go
internal/config/config_test.go
internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
pkg/client/client_test.go
pkg/lib.go
pkg/lib_test.go
pkg/mode/mode_test.go
test/integration/get_images_test.go

- **feat: bump go version to 1.22**
- **feat: add account routing for namespaces**

feat: add account routing

---

README.md
anchore-k8s-inventory.yaml
cmd/root.go
pkg/inventory/namespace.go
pkg/lib.go
pkg/reporter/reporter.go

- **chore: add some debug logs for account routing**
- **chore: update README with account routing config options**
- **fix: ensure correct handling for missing anchore account**

fix: account routing updates

---

README.md
anchore-k8s-inventory.yaml

chore: make account routing example clearer

---

pkg/lib.go

chore: improve logging for namespace collection

---

README.md
anchore-k8s-inventory.yaml
internal/config/config.go
internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
pkg/inventory/namespace.go
pkg/inventory/namespace_test.go
pkg/inventory/nodes.go
pkg/inventory/nodes_test.go
pkg/inventory/pods.go
pkg/inventory/pods_test.go
pkg/lib.go

- **fix: calculate batch count outside of loop**
- **feat: first part of configurable metadata-collection**

feat: first part of configurable metadata-collection

---

.github/workflows/release.yaml

fix: temp unblock the release action

---

.github/workflows/release.yaml

fix: temp unblock the release workflow

---

.github/workflows/release.yaml
.goreleaser.yaml

ci: add back fixed release checks

---

README.md

chore: fix helm install commands in readme

---

.gitignore
pkg/lib.go
pkg/lib_test.go

- **chore: add cover.cov to gitignore**
- **feat: rework the batching logic**
Calculate batches at the end of the inventory workflow

feat: rework batch workflow

---

.gitignore
README.md
pkg/inventory/namespace.go
pkg/inventory/namespace_test.go
pkg/inventory/nodes.go
pkg/inventory/nodes_test.go
pkg/inventory/pods.go
pkg/inventory/pods_test.go
pkg/inventory/util.go
pkg/inventory/util_test.go
pkg/lib.go
pkg/lib_test.go

- **chore: add cover.cov to gitignore**
- **feat: rework the batching logic**
- **feat: add util function for processing namespaces/labels**
- **feat: add ability to include specific namespace annotations/labels**
- **feat: add ability to include specific pod annotations/labels**
- **feat: add ability to include specific node annotations/labels**
- **chore: update README for metadata collection**

feat: custom annotations/labels

---

pkg/integration/integration.go

chore: reduce max polling time from 24 hours to 1 hour

---

pkg/integration/integration.go
pkg/integration/integration_test.go

fix: integration registration should reuse the integration registration name

---

README.md

docs: add entitlement notice
