- CONTRIBUTING.md
- Dockerfile
Right now kai will fail in-cluster whenever any kind of TLS is required. Golang uses the environments SSL certs and none of those are present in the `scratch` container. I'm just changing the underlying container to distroless which comes with ca certs bundled. Also putting the config flag in a `CMD` so it'll find the config that the chart mounts in.
Signed-off-by: James Petersen <jpetersenames@gmail.com>
> Change the underlying container to distroless

- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- kai.yaml
- kai/lib.go
Implement a worker pool for the pod collection. That way the api server does not get overwhelmed when there are 1000's of namespaces.
I had a whole worker pool package implementation based off https://github.com/found-it/worker-pools but it started to get messy so I decided to keep it simple with the anonymous function. Happy to hear some feedback
Other minor change: kai will collect all namespaces if the `namespaces` config is an empty list. That way we avoid a conflict if the end user has a namespace named "all"
> Implement a worker pool

- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- kai.yaml
- kai/inventory/reportitem.go
- kai/inventory/reportitem_test.go
- kai/lib.go
Attempt to parse the unique image details using a few more fields in the pod object along with some regexes.
Also added an `ignore-not-running` option so the end user can configure whether they want to capture image details from pods that are not running yet.
> Improve the ReportImage parsing

- .gitignore
- cmd/root.go
- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- kai.yaml
- kai/inventory/reportitem.go
- kai/lib.go
- test/integration/get_images_test.go
kai.yaml contained a typo in regards to which keyword
golang was looking for to set the http.timeout-seconds mapstructure.
The following changes updates the config file and the required golden
test file to reflect this change.
Signed-off-by: Toure Dunnon <toure.dunnon@anchore.com>
fixes: https://github.com/anchore/kai/issues/33
> Kai default configuration has a typo

- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- kai.yaml
- kai/inventory/reportitem.go
- kai/inventory/reportitem_test.go
- kai/lib.go
There is still one case where a tag cannot be parsed out of a pod spec. When an image is added by digest only
for example
```sh
kubectl run python --image=python@sha256:f0a210a37565286ecaaac0529a6749917e8ea58d3dfc72c84acfbfbe1a64a20a --command -- sleep inf
```
This causes issue in Anchore Enterprise because it requires a tag. To remedy this in kai there are a couple options
1. Use the digest as the tag
2. Insert a dummy tag (specified by the end user)
3. Drop the image from the report
> Handle the null tag edge case

- Makefile
The install script for go-bouncer is load-bearing; it will download a
license database that it uses for scanning licenses. The Makefile was
updated to use the install script to install bouncer instead of through
go install.
The versions for goreleaser, golang-ci, and go-bouncer are also now
included as constants at the top of the Makefile to make future
modifications to the versions easier.
Signed-off-by: Dustin Schoenbrun <dustin.schoenbrun@anchore.com>
Co-Authored by: Weston Steimel <weston.steimel@anchore.com>
> Fix Go-Bouncer Installation

- .golangci.yaml
- kai/inventory/reportitem.go
- kai/lib.go
While running the Lint checks for KAI, I noticed that a couple of the
linters that golangci-lint was using were deprecated and had been
replaced by other, supported linters.
```
golint --> revive
scopelint --> exportloopref
```
This patch also fixes new linter issues found by these updated linters.
Signed-off-by: Dustin Schoenbrun <dustin.schoenbrun@anchore.com>
> Update Go Linters and Fix New Lint Errors

- .gitignore
- Dockerfile.skaffold
- Makefile
- README.md
- cmd/root.go
- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- internal/tracker/time.go
- kai/lib.go
- kai/reporter/reporter.go
- skaffold.yaml
- chore: adds support for using skaffold for development
- feat: change default logging level to Info
- feat: no longer output inventory reports to stdout by default
- feat: log function execution times
- chore: add some useful info logs
Example of the log output with these changes:
```
[kai] [2023-03-21 23:33:08]  INFO KAI is starting up...
[kai] [2023-03-21 23:33:08]  INFO Starting image inventory collection
[kai] [2023-03-21 23:33:08] DEBUG using in-cluster kube config
[kai] [2023-03-21 23:33:08] DEBUG Fetching namespaces took 68.73675ms
[kai] [2023-03-21 23:33:08]  INFO There are 0 pods in namespace "kube-node-lease"
[kai] [2023-03-21 23:33:08] DEBUG Fetching pods in namespace: kube-node-lease took 41.1165ms
[kai] [2023-03-21 23:33:08]  INFO There are 0 pods in namespace "kube-public" …
```
> feat: improve logging

- .goreleaser.yaml
- Makefile
A new build has been added that uses CGO and the boring crypto build
flag to substitute go's default crypto library with boring crypto to
ensure the binary can run on FIPs enabled hosts. The fips build includes
the go symbol table in the binary (note other builds include -s to strip
it), this allows you to run `go tool nm anchore-k8s-inventory | grep
'_Cfunc__goboringcrypto_'` to verify that the binary was built with
boringcrypto.
A new docker image will also be built with the tag `{{TAG}}-fips-amd64`
that includes the -fips binary.
> feat: add a build that uses boring crypto to run on fips enabled hosts

- pkg/reporter/reporter.go
- pkg/reporter/reporter_test.go
Go's http client will automatically follow redirects, we want to preserve the ability to follow redirects but we need to catch cases where the redirect returns a 2XX status but the POST was not actually successful. A simple check is read the response body (if one is present) and check if it is valid JSON. If it is not JSON, as is the case with cloudflare where it redirects to a login screen then we can return an error and log the response body to give customers an indication of where the redirect has taken them so it can be remediated at the proxy
> fix: try to catch invalid responses on Enterprise API redirect

- pkg/reporter/reporter.go
- pkg/reporter/reporter_test.go
- fix: remove unnecessary println
- test: change reporter tests to use respond with 201
> test: use 201 responses in UTs to better represent the Enterprise API

- .golangci.yaml
We don't have configuration for this yet
> chore: remove depguard from golangci

- README.md
Fixes 'master' to 'main' as used in the chart repo. Fixes a broken link for the values yaml.
> Update README.md to fix chart link to correct branch

- Dockerfile
- Dockerfile.skaffold
- skaffold.yaml
- feat: change base image to scratch container
- chore: fix skaffold build for dev
Changing to a scratch container that just pulls in the SSL certs from the
debian distroless image to reduce the vuln surface in the image.
> feat: change docker image to scratch container

- README.md
- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
Reverts anchore/k8s-inventory#164 until the next major version bump as this will be a breaking change for users
> Revert "feat: change default http timeout from 10 to 60 seconds"

- pkg/lib.go
If verbose-inventory-reports is set to true, to aid debugging we should log the report to
stdout even in the case of an error from Enterprise during the post.
> fix: ensure that inventory report is logged on post error

- README.md
- anchore-k8s-inventory.yaml
- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- pkg/lib.go
if `ignore-empty` is true under the namespace-selectors config section
then if the namespace contains no pods then it will not be included in
the report sent to Anchore Enterprise.
> feat: add option to ignore empty namespaces

- anchore-k8s-inventory.yaml
- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- pkg/inventory/containers.go
- pkg/inventory/containers_test.go
- pkg/lib.go
If kubernetes does not provide a registry for an image give the option
to return the pull string to Anchore Enterprise with a default registry
set for the image.
> feat: add missing registry override

- Makefile
- README.md
- anchore-k8s-inventory.yaml
- cmd/root.go
- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- pkg/lib.go
- pkg/lib_test.go
- test/integration/get_images_test.go
If a limit for number of namespaces is set in config then upon reaching
this limit break up the number of namespaces into batches of that size
or lower for sending to Anchore.
NOTE: lowered coverage limit temporarily
> feat: add batch sending of inventory reports based on limits

- go.mod
- scripts/install-go.sh
> feat: bump go to 1.22.5

- go.mod
- go.sum
- internal/config/config.go
- internal/config/config_test.go
- internal/config/kube_config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigJSON.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
This commit makes changes so that all passwords and private keys are redacted in logs, when json marshalled and when yaml marshalled.
Addresses: ENTERPRISE-4159
> fix: redact passwords under account-routes

- internal/config/config.go
Error returns from reading the config were being ignored so if the config file doesn't exist we just proceeded with using the default config.
See Issue #269 for more context.
> fix: ensure missing config errors are caught

- anchore-k8s-inventory.yaml
- internal/config/config.go
- internal/config/test-fixtures/snapshot/TestDefaultConfigString.golden
- internal/config/test-fixtures/snapshot/TestEmptyConfigString.golden
- internal/config/test-fixtures/snapshot/TestSensitiveConfigString.golden
- pkg/lib.go
- pkg/lib_test.go
[ENTERPRISE-6042](https://anchore.atlassian.net/browse/ENTERPRISE-6042)
Adds an additional option to `inventory-report-limits` with a new setting for `payload-bytes`.
When `payload-bytes` is specified, we will perform batching on a namespace boundary as before, but include a dynamic number of namespaces in each batched report based on a rough measure of the overall size of the payload, rather than a fixed count of namespaces.
If both are set, then a new batch will be started when either limit is reached.
[ENTERPRISE-6042]: https://anchore.atlassian.net/browse/ENTERPRISE-6042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: batch inventory reports by payload size
